// This is a comment to explain the purpose of this file.
// This file contains all the action types for the Redux actions.

export const FETCH_SELLERS_REQUEST = 'FETCH_SELLERS_REQUEST';
export const FETCH_SELLERS_SUCCESS = 'FETCH_SELLERS_SUCCESS';
export const FETCH_SELLERS_FAILURE = 'FETCH_SELLERS_FAILURE';

export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

export const FETCH_SHOPS_REQUEST = 'FETCH_SHOPS_REQUEST';
export const FETCH_SHOPS_SUCCESS = 'FETCH_SHOPS_SUCCESS';
export const FETCH_SHOPS_FAILURE = 'FETCH_SHOPS_FAILURE';

export const FETCH_PAYMENTS_REQUEST = 'FETCH_PAYMENTS_REQUEST';
export const FETCH_PAYMENTS_SUCCESS = 'FETCH_PAYMENTS_SUCCESS';
export const FETCH_PAYMENTS_FAILURE = 'FETCH_PAYMENTS_FAILURE';

export const FETCH_REPORTS_REQUEST = 'FETCH_REPORTS_REQUEST';
export const FETCH_REPORTS_SUCCESS = 'FETCH_REPORTS_SUCCESS';
export const FETCH_REPORTS_FAILURE = 'FETCH_REPORTS_FAILURE';

// Admin product moderation actions
export const APPROVE_PRODUCT = 'APPROVE_PRODUCT';
export const REJECT_PRODUCT = 'REJECT_PRODUCT';
export const REQUEST_PRODUCT_MODIFICATION = 'REQUEST_PRODUCT_MODIFICATION';
export const APPROVE_PRODUCT_VARIANTS = 'APPROVE_PRODUCT_VARIANTS';

// Admin shop moderation actions
export const APPROVE_SHOP = 'APPROVE_SHOP';
export const REJECT_SHOP = 'REJECT_SHOP';
export const REQUEST_SHOP_MODIFICATION = 'REQUEST_SHOP_MODIFICATION';

// Orders
export const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE';
export const UPDATE_ORDER_STATUS = 'UPDATE_ORDER_STATUS';

// Support tickets
export const FETCH_TICKETS_REQUEST = 'FETCH_TICKETS_REQUEST';
export const FETCH_TICKETS_SUCCESS = 'FETCH_TICKETS_SUCCESS';
export const FETCH_TICKETS_FAILURE = 'FETCH_TICKETS_FAILURE';
export const ADD_TICKET_MESSAGE = 'ADD_TICKET_MESSAGE';
export const UPDATE_TICKET_STATUS = 'UPDATE_TICKET_STATUS';
